name: 'Setup Node.js Project'
description: 'Composite action to checkout code, setup Node.js, and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
